name: pytorch
channels:
- conda-forge
dependencies:
- python=3.12.9
- pip<=25.1
- pip:
  - --extra-index-url https://download.pytorch.org/whl/cu128
  - polars==1.30.0
  - pillow==11.0.0
  - plotly==5.24.1
  - nbformat==5.10.4
  - torch==2.7.0+cu128
  - torchvision==0.22.0+cu128
  - torchinfo==1.8.0
  - lightning==2.5.1.post0
  - mlflow==3.2.0
  - psutil==7.0.0
  - pynvml==12.0.0
  - nannyml==0.13.1
  - lakefs==0.11.1
  - aiobotocore==2.23.1
  - boto3==1.38.44
  - SQLAlchemy==2.0.41
  - psycopg2==2.9.10
  - fastapi==0.115.12
  - python-multipart==0.0.20
  - streamlit==1.48.0
  - prefect==3.4.6